### ISSUE TITLE
Unknown warning on Java 10 

### ISSUE THREAD

**Issue by dampion** [rest-assured/rest-assured#1027]
```
import io.restassured.RestAssured;

public static main(String[] org) {
	public static void main(String[] org) {
	}
}
```

after running the above set with eclipse which includes the lib from restAssured, the result below will show up and still can't find the reason. Is there anyone able to resolve it? 

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/dampion/Tools/java-rest-assured/rest-assured-3/rest-assured-3.1.0-deps/groovy-2.4.12.jar) to method java.lang.Object.finalize()
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by kaydeeH** [comment]
Same error on Java 9.

**Comment by johanhaleby** [comment]
Could this be due to the groovy version used? Could you try excluding groovy from rest-assured (see faq) and update to a newer version of groovy to see if it goes away?

**Comment by Jazzepi** [comment]
@johanhaleby I upgraded the version of groovy I'm using locally from 2.4.12 (the version rest-assured depends on) to version 2.5.1 (the latest stable release of Groovy-all).

Here's my dependency tree showing the 2.4.12 getting overridden by the 2.5.1 dependency.
```
+--- io.rest-assured:rest-assured:3.1.0
|    +--- org.codehaus.groovy:groovy-xml:2.4.12 -> 2.5.1
|    |    \--- org.codehaus.groovy:groovy:2.5.1
|    +--- org.apache.httpcomponents:httpclient:4.5.3
|    |    +--- org.apache.httpcomponents:httpcore:4.4.6
|    |    \--- commons-codec:commons-codec:1.9 -> 1.11
|    +--- org.apache.httpcomponents:httpmime:4.5.1
|    |    \--- org.apache.httpcomponents:httpclient:4.5.1 -> 4.5.3 (*)
|    +--- org.hamcrest:hamcrest-core:1.3
|    +--- org.hamcrest:hamcrest-library:1.3 (*)
|    +--- org.ccil.cowan.tagsoup:tagsoup:1.2.1
|    +--- io.rest-assured:json-path:3.1.0
|    |    +--- org.codehaus.groovy:groovy-json:2.4.12 -> 2.5.1
|    |    |    \--- org.codehaus.groovy:groovy:2.5.1
|    |    \--- io.rest-assured:rest-assured-common:3.1.0
|    |         \--- org.apache.commons:commons-lang3:3.4
|    \--- io.rest-assured:xml-path:3.1.0
|         +--- org.codehaus.groovy:groovy-xml:2.4.12 -> 2.5.1 (*)
|         +--- io.rest-assured:rest-assured-common:3.1.0 (*)
|         +--- org.apache.commons:commons-lang3:3.4
|         +--- org.ccil.cowan.tagsoup:tagsoup:1.2.1
|         \--- javax.xml.bind:jaxb-api:2.2.12
\--- org.codehaus.groovy:groovy-all:2.5.1
     +--- org.codehaus.groovy:groovy:2.5.1
     +--- org.codehaus.groovy:groovy-ant:2.5.1
     |    +--- org.codehaus.groovy:groovy:2.5.1
     |    +--- org.apache.ant:ant:1.9.9
     |    |    \--- org.apache.ant:ant-launcher:1.9.9
```

Still getting the same problem though.

I've spent all of 10 minutes looking into this, but I think this may be code inside of rest-assured that needs to be changed.

Here's another project that had the same issue. There's also a commit there showing how they fixed it.
https://github.com/jqno/equalsverifier/issues/183

**Comment by lu-ko** [comment]
Multiple Groovy issues (e.g. mentioned [GROOVY-8339](https://issues.apache.org/jira/browse/GROOVY-8339) and [GROOVY-9070](https://issues.apache.org/jira/browse/GROOVY-9070) or [GROOVY-8843](https://issues.apache.org/jira/browse/GROOVY-8843) are already CLOSED. Do you have any update from REST Assured point of view?

**Comment by Jazzepi** [comment]
Two of these are marked as fixed in Groovy 3.0 alpha/beta

I don't expect REST assured will do anything until Groovy 3.0 has an
official release.

**Comment by kullingsjo** [comment]
I get this warning on Java 11. Using rest-assured 4.2.0 with dependency to groovy 2.5.9. Groovy 3.0.0 is available since feb. Will rest-assured be updated shortly?

**Comment by zhe-zhao** [comment]
For people who searching for an answer. Start from version 4.3.0 RestAssured have upgraded from groovy 2.5.7 to 3.0.*
It fixes that annoying warning when you're running your app on jvm11 or above

**Comment by sasuw** [comment]
@zhe-zhao I still get the warning using Java 11 and rest-assured 4.4.0, which uses groovy 3.0.8.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/sasu/.m2/repository/org/codehaus/groovy/groovy/3.0.8/groovy-3.0.8.jar) to constructor java.lang.AssertionError(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
