### ISSUE TITLE
memory leak using JsonPath.from(string).getUUID()

### ISSUE THREAD

**Issue by vguna** [rest-assured/rest-assured#735]
Hi.

I'm performing loadtests using RestAssured 2.9.0 against a REST service. For this, I check the returned response id against a UUID using:

`JsonPath.from(jsonString).getUUID("id");`

I encountered, that during the tests, memory consumption grows and dies in the end with OOME. Tracking down the consumption shows, that many classes of

`org.codehaus.groovy.runtime.metaclass.MetaMethodIndex$Entry`

are loaded and never freed. It seems having something todo with the `getUUID()` method on RestAssured's side. Just parsing the json string with `JsonPath.from()` doesn't seem to leak.

I think it's a Groovy problem, which is tracked here: 

https://issues.apache.org/jira/browse/GROOVY-7683

But maybe meanwhile you guys could workaround it somehow? Since currently it is unusable for me. I will use a workaround not using `getUUID()` for now.

Here a simple snippet to reproduce the problem:

``` java
    public static void main(String[] args) throws InterruptedException {
        for (int ci = 0; ci < 100000; ci++) {
            JsonPath.from("{\"id\": \"" + UUID.randomUUID().toString() + "\"}").getUUID("id");
            Thread.sleep(1);
        }
    }
```

Thanks!

Just wanted to add: it seems that it happens to all `.get*` methods - not just `.getUUID()`.

**Comment by johanhaleby** [comment]
Ouch. You don't happen to know how to track this down? Is REST Assured holding references to the created instances somehow?

**Comment by vguna** [comment]
Actually I don't really know. That's the reason why I also joined the ticket on the Groovy issue tracker. Maybe there's more detail for you guys to dig into and join the party :)? Since it's not just `getUUID()` but, as it seems, all `get*` on JsonPath I switched to https://github.com/jayway/JsonPath which is a little bit different to use, but doesn't seem to be affected. Maybe because it doesn't use Groovy :)?

BTW: what's the reason behind the two different JsonPath implementations from you guys :)?

**Comment by RocketRaccoon** [comment]
It looks like we've faced with the same issue. Test execution jenkins slaves regulary fails with OOME. We have a lot of such calls `JsonPath.from(string).get*()` in test code.

**Comment by johanhaleby** [comment]
This is of course quite a serious issue but I'm in the middle of moving and we're expecting a new child any day now so I personally won't have time to dig into this in a foreseeable future. It was quite a long time ago that I tracked down memory leaks so I' essentially have to relearn the tooling.    I'd love if anyone one of you could help out.

**Comment by RocketRaccoon** [comment]
Just for information, `ValidatableResponse.body()` have the same issue.

**Comment by johanhaleby** [comment]
Must be some evil static reference somewhere that is not released properly. If you guys have a heap dump could you share it here or run it in Eclipse MAT? If I remember it correctly (and we're lucky) it might be able to find it automatically.

**Comment by RocketRaccoon** [comment]
It seems that com.jayway.restassured.internal.path.json.JSONAssertion causing memory leak.

**Comment by johanhaleby** [comment]
Thanks. How did you figure that out? Is it possible to be even more specific? A groovy shell is executed from this class, could that be perhaps be (part of?) that cause?!

**Comment by RocketRaccoon** [comment]
I had a bit of time to run vguna's case and analyze dump at MAT (VirtualVM is failing on creation snapshot with stacktrace), it mentioned on this class. I will try to spend more time on the issue tomorrow.

**Comment by johanhaleby** [comment]
Thanks a lot Andrey, really appreciate your help.

**Comment by RocketRaccoon** [comment]
Hi,
Please see pull request. I spend some time playing with options and versions and have found that at 2.9.1 it worked fine, it uses groovy 2.4.4. There was change related to [GROOVY-7591](https://issues.apache.org/jira/browse/GROOVY-7591) about disabling ClassValue, that is why I enabled it back.  Also I have removed static method and add `sh.resetLoadedClasses()` (can't make it work without that cleaning). Got the followint statistic on example above: 
![image](https://cloud.githubusercontent.com/assets/3246428/17807941/b24f7a48-6615-11e6-8df4-deff25e5dbb5.png)
Before fix it looked like this one:
![image](https://cloud.githubusercontent.com/assets/3246428/17807972/f9585a40-6615-11e6-8bc6-90ed4463c09c.png)

**Comment by RocketRaccoon** [comment]
For 2.9.0 it was enough to run with ` -Dgroovy.use.classvalue=true`

**Comment by jhasenauer** [comment]
Is it possible for com.jayway.restassured.assertion.XMLAssertion to cause a similar memory leak?

**Comment by johanhaleby** [comment]
@RocketRaccoon Thank you sooo much for your investigation. But the leak is still there if `ClassValue` is false? (which is default?)

**Comment by johanhaleby** [comment]
@jhasenauer I would suppose so? I've added `resetLoadedClasses()` to XmlAssertion as well to be safe. Thanks for the tip.

**Comment by RocketRaccoon** [comment]
@johanhaleby It seems that I was wrong about 2.9.0 :( You are right, this option is default, I have rechecked it again and got the issue with GC. 
![image](https://cloud.githubusercontent.com/assets/3246428/17844114/97c6f158-683e-11e6-911b-f337484491d4.png)

**Comment by RocketRaccoon** [comment]
I have run some additional tests on 2.9.0 and found that using `GroovyShell.resetLoadedClasses()` and `-Dgroovy.use.classvalue=false` make it work.

**Comment by johanhaleby** [comment]
@RocketRaccoon Thanks again! It's very unfortunate that it only works the JVM is started with `-Dgroovy.use.classvalue=false`. What does "disabling ClassValue" actually do? I wonder if there's something we can do to avoid this situation without having to use a JVM param.

**Comment by RocketRaccoon** [comment]
I'm not so good at JDK infrastructure and do not know what is using when it's bisabled, but the root issue which causes that changes in groovy is this one https://bugs.openjdk.java.net/browse/JDK-8136353

**Comment by vguna** [comment]
I'm a bit confused now :). So it has been fixed, since it's closed. So do I have to provide that additional JVM option or not when using 2.9.1 (?) in the future?

**Comment by johanhaleby** [comment]
Sorry guys, closed the wrong issue. Font really know how we should proceed here.

**Comment by RocketRaccoon** [comment]
imho, the best option is to wait fix in groovy (2.4.8 ?) and test it with rest assured to avoid using any additional run options

**Comment by johanhaleby** [comment]
@RocketRaccoon Thanks for your input, I think that sounds good.

**Comment by vguna** [comment]
Hi guys.

Just upgraded to Rest Assured 3.0.5 and Groovy 2.4.9 hoping this leak is fixed. Apparently it is not :(. Please find attached a test-run using the initial lines of code I posted. I also tried `-Dgroovy.use.classvalue=false` with the same effect.

Anything I'm missing here :)?

![pasted image at 2017_11_06 03_35 pm](https://user-images.githubusercontent.com/3257311/32446383-ff507576-c308-11e7-8aba-21ded27852b3.png)

**Comment by RocketRaccoon** [comment]
@vguna do you have any reproducible example to share?

**Comment by RocketRaccoon** [comment]
For the moment can just confirm that issue is reproducing. Also the same is happening with 2.4.11 - old gen is not clearing.

**Comment by RocketRaccoon** [comment]
Actually, works fine with enabled `-Dgroovy.use.classvalue=true`
![image](https://user-images.githubusercontent.com/3246428/32482128-596f1a28-c3a7-11e7-952c-0eb141641ba9.png)
![image](https://user-images.githubusercontent.com/3246428/32482143-67347bbc-c3a7-11e7-96d5-a2a56235fe1e.png)
![image](https://user-images.githubusercontent.com/3246428/32482149-711966a6-c3a7-11e7-9281-3eec504655bd.png)

**Comment by walbx** [comment]
I am afraid it's not fixed.

rest-assured:3.0.6
groovy:2.4.12
vm:-Dgroovy.use.classvalue=true

` 
      JsonPath.from("{\"msg\": \"error\"}").get("msg");
`


![4-3](https://user-images.githubusercontent.com/9149989/34244407-1c5e6cb6-e660-11e7-96ff-dd4833fd3953.png)
![4-2](https://user-images.githubusercontent.com/9149989/34244410-1e1aca9a-e660-11e7-8c66-0df6d49de39f.png)
![4-4](https://user-images.githubusercontent.com/9149989/34244839-270a76b2-e662-11e7-900e-2143d523b4cc.png)
